title: Brian S. Cho # your name (or website title) here
logo: "/images/resume photo2.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Brian's portfolio
  <br><br>
  <a href="https://www.linkedin.com/in/brian-cho-9072b217a/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
